# -*- coding: utf-8 -*-
"""python_task_2.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/183pGmPLt43jD0aAgi5GQOKj9W5I-jfv6
"""

def calculate_distance_matrix(df)->pd.DataFrame():
    df['cumulative_distance'] = df['distance'].cumsum()
    df_result = pd.DataFrame(index=df["id_start"], columns=df["id_start"])

    for i in range(len(df)-1):
      df_result.at[1001400,df_result.columns[i+1]]=df.loc[i,"cumulative_distance"]

    for i in range(len(df_result)-1):
      if i==0:
        continue
      value_sum=0
      for j in range(len(df_result)):
        if i>j:
          continue
        df_result.loc[df_result.index[i],df_result.columns[j]]=value_sum
        #print(i+j)
        value_sum+=df.iloc[j,2]
    df_result.fillna(0, inplace=True)
    c=df_result.T.copy()
    df_result+= c
    return df_result